# Top level comment

import (
    # Internal documentation

    "one.gql"

    # Another internal documentation
    "two.gql"
)

"Schema description"
schema @one @two() @three(a: A) {
    "Query description"
    query: Query

    "Mutation description"
    mutation: Mutation

    "Subscription description"
    subscription: Subscription
}

# TODO: Object, Interface, Union, Enum, Input, Description