// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	ast "github.com/gqlc/graphql/ast"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// An encoded PluginRequest is written to the plugin's stdin.
type Request struct {
	// The .gql/.graphql files to generate.
	FileToGenerate []string `protobuf:"bytes,1,rep,name=file_to_generate,json=fileToGenerate,proto3" json:"file_to_generate,omitempty"`
	// The generator parameter passed on the command-line encoded as JSON.
	Parameter string `protobuf:"bytes,2,opt,name=parameter,proto3" json:"parameter,omitempty"`
	// Documents are all the parsed documents to be generated.
	Documents            []*ast.Document `protobuf:"bytes,3,rep,name=documents,proto3" json:"documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetFileToGenerate() []string {
	if m != nil {
		return m.FileToGenerate
	}
	return nil
}

func (m *Request) GetParameter() string {
	if m != nil {
		return m.Parameter
	}
	return ""
}

func (m *Request) GetDocuments() []*ast.Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

// The plugin writes an encoded PluginResponse to stdout.
type Response struct {
	// Error message. If non-empty code generation failed. The plugin
	// process should exit with status code zero even if it reports
	// an error in this way.
	//
	Error                string           `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	File                 []*Response_File `protobuf:"bytes,2,rep,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetFile() []*Response_File {
	if m != nil {
		return m.File
	}
	return nil
}

// Represents a single generated file.
type Response_File struct {
	// The file name, relative to the output directory. The name must not
	// contain "." or ".." components and must be relative, not be absolute (so,
	// the file cannot lie outside the output directory). "/" must be used as
	// the path separator, not "\".
	//
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The file contents.
	Content              string   `protobuf:"bytes,15,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_File) Reset()         { *m = Response_File{} }
func (m *Response_File) String() string { return proto.CompactTextString(m) }
func (*Response_File) ProtoMessage()    {}
func (*Response_File) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{1, 0}
}

func (m *Response_File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_File.Unmarshal(m, b)
}
func (m *Response_File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_File.Marshal(b, m, deterministic)
}
func (m *Response_File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_File.Merge(m, src)
}
func (m *Response_File) XXX_Size() int {
	return xxx_messageInfo_Response_File.Size(m)
}
func (m *Response_File) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_File.DiscardUnknown(m)
}

var xxx_messageInfo_Response_File proto.InternalMessageInfo

func (m *Response_File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Response_File) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*Response_File)(nil), "Response.File")
}

func init() { proto.RegisterFile("plugin.proto", fileDescriptor_22a625af4bc1cc87) }

var fileDescriptor_22a625af4bc1cc87 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x50, 0xc1, 0x6a, 0xeb, 0x30,
	0x10, 0xc4, 0xb1, 0x5f, 0x62, 0xed, 0x2b, 0x69, 0x11, 0x85, 0x08, 0x53, 0xa8, 0xf1, 0xc9, 0xbd,
	0x28, 0x90, 0xb6, 0x7f, 0x50, 0xda, 0x6b, 0x11, 0xbd, 0x07, 0xc5, 0xdd, 0x18, 0x83, 0x2d, 0x39,
	0xd2, 0xfa, 0xd2, 0x2f, 0xe8, 0x67, 0x17, 0x2b, 0x76, 0x72, 0xdb, 0x99, 0x59, 0x66, 0x67, 0x07,
	0x6e, 0xfa, 0x76, 0xa8, 0x1b, 0x23, 0x7b, 0x67, 0xc9, 0x66, 0x9b, 0xfa, 0xd4, 0x56, 0xdb, 0x30,
	0x1f, 0x86, 0xe3, 0x56, 0x7b, 0x3a, 0x0b, 0xc5, 0x6f, 0x04, 0x2b, 0x85, 0xa7, 0x01, 0x3d, 0xf1,
	0x12, 0xee, 0x8e, 0x4d, 0x8b, 0x7b, 0xb2, 0xfb, 0x1a, 0x0d, 0x3a, 0x4d, 0x28, 0xa2, 0x3c, 0x2e,
	0x99, 0x5a, 0x8f, 0xfc, 0x97, 0xfd, 0x98, 0x58, 0xfe, 0x00, 0xac, 0xd7, 0x4e, 0x77, 0x48, 0xe8,
	0xc4, 0x22, 0x8f, 0x4a, 0xa6, 0xae, 0x04, 0x7f, 0x05, 0xf6, 0x6d, 0xab, 0xa1, 0x43, 0x43, 0x5e,
	0xc4, 0x79, 0x5c, 0xfe, 0xdf, 0x6d, 0xe4, 0x18, 0x40, 0xce, 0x01, 0xe4, 0xdb, 0xa4, 0xab, 0xeb,
	0x66, 0xf1, 0x03, 0xa9, 0x42, 0xdf, 0x5b, 0xe3, 0x91, 0xdf, 0xc3, 0x3f, 0x74, 0xce, 0x3a, 0x11,
	0x05, 0xf3, 0x33, 0xe0, 0x05, 0x24, 0x63, 0x10, 0xb1, 0x08, 0x9e, 0x6b, 0x39, 0xaf, 0xcb, 0xf7,
	0xa6, 0x45, 0x15, 0xb4, 0xec, 0x05, 0x92, 0x11, 0x71, 0x0e, 0x89, 0xd1, 0x1d, 0x4e, 0x06, 0x61,
	0xe6, 0x02, 0x56, 0x95, 0x35, 0x84, 0x86, 0xc4, 0x6d, 0xa0, 0x67, 0xb8, 0x7b, 0x82, 0xe5, 0x67,
	0xe8, 0x8b, 0x3f, 0x42, 0x7a, 0x79, 0x33, 0x95, 0x53, 0x35, 0x19, 0xbb, 0xdc, 0x3a, 0x2c, 0xc3,
	0x13, 0xcf, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x44, 0x71, 0x9d, 0x1c, 0x61, 0x01, 0x00, 0x00,
}
